version: "3.6"

services:
  node:
    image: node:18.9.1-alpine
    command: /bin/sh -c "yarn install && yarn migrate && yarn start"
    restart: on-failure
    volumes:
      - ./:/dsm_pi_quarto_semestre:Z
    ports:
      - "127.0.0.1:3030:3000"
    working_dir: /dsm_pi_quarto_semestre
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgres:Z
