version: "3.6"

services:
  node:
    image: node:18.9.1-alpine
    command: /bin/sh -c "yarn install && yarn migrate && yarn start"
    restart: on-failure
    volumes:
      - ./:/dsm_pi_quarto_semestre:Z
    ports:
      - "127.0.0.1:3030:3000"
    working_dir: /dsm_pi_quarto_semestre
    env_file:
      - .env
