name: Build and publish mobile app

on:
  push:
    branches:
      - main
    paths:
      - mobile/**
      - .github/**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into source code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant Gradlew execution permission
        run: chmod +x ./mobile/gradlew

      - name: Create signing key
        run: echo "${{ secrets.KEYSTORE_BASE }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks

      - name: Build signed app
        run: |
          cd ./mobile
          ./gradlew build
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSW }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSW }}

      - name: Publish app to Github releases
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # file: ./mobile/app/build/outputs/apk/release/app-release-unsigned.apk
          file: ./mobile/app/build/outputs/apk/release/app-release.apk
          draft: false
