name: Build app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Grant Gradlew permission
        run: chmod +x ./mobile/gradlew

      - name: Build
        run: ./mobile/gradlew build
