name: Build app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into source code
        uses: actions/checkout@v2
      
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Grant Gradlew execution permission
        run: chmod +x ./mobile/gradlew

      - name: Build app
        run: cd ./mobile && ./gradlew build
