name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: placeholder

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: ssh -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_IP }} "cd ${{ secrets.DEPLOY_PATH }} && git pull --ff-only && docker-compose -f production.yml down && docker-compose -f production.yml up -d"
